{{- if and .Values.didJson.enabled .Values.didJson.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: did-json
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- with .Values.didJson.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.didJson.ingress.host  | quote }}
      secretName: cert-chain
  rules:
    - host: {{ .Values.didJson.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: did-json
                port:
                  name: http
{{- end }}
